### ISSUE TITLE
wheel_vel

### ISSUE THREAD

**Issue by agrytnes** [eborghi10/my_ROS_mobile_robot#4]
First of all I want to thank you for uploading your code. Its been of great help to implement ros_control for my custom robot.

I have one issue though: 

Im using ps4 controller to publish /mobile_base_controller/cmd_vel. The output is between -1 and 1.

Am I right if the /my_robot/left_wheel_vel and /my_robot/right_wheel_vel output also should be between -1 and 1?

When I go straight forward or backwards /my_robot/left_wheel_vel and /my_robot/right_wheel_vel output always is -1 or 1. In other words full speed backwards or full speed forward. Even when _/mobile_base_controller/cmd_vel output is e.g. 0.5. 
When turning /my_robot/left_wheel_vel and /my_robot/right_wheel_vel output is working perfectly between -1 and 1 according to ps4 cmd_vel.

Have you any idea on where to start looking? 

Thanks
Andreas

**Comment by eborghi10** [comment]
Hi Andreas, I didn't understand something. Is your PS4 controller node output between -1 and 1?

Also, if I remember correctly, the wheel velocity topics are used on the real robot, not the simulation.

There is a difference between cmd_vel and those velocities because the first one it's the command for the robot, and the others, for each wheel. The first two equations [here](http://planning.cs.uiuc.edu/node659.html) show you the difference.

HTH, Emiliano.

**Comment by agrytnes** [comment]
Yes, my ps4 controller node output is between -1 and 1 on the cmd_vel topic.

I'm running this on a real robot. I use an arduino to subscribe to /my_robot/left_wheel_vel and /my_robot/right_wheel_vel. Because I only get wheel_vel between -1 and 1 I multiply it by 255(which is max pwm input on motor driver)

Even if I use "rostopic pub -r 100 ... /mobile_robot_controller/cmd_vel..." with x value bigger than 1 the wheel_vel is never greater than 1 .

**Comment by eborghi10** [comment]
Could you send me a picture of your `rqt_graph` showing all the nodes/topics?

**Comment by agrytnes** [comment]
![image](https://user-images.githubusercontent.com/23460540/44286624-09d53180-a26a-11e8-8c19-59dccc57e6ac.png)

**Comment by eborghi10** [comment]
Did you check that the `/my_robot_base_node` is working correctly if you set the velocity values directly through the terminal instead of using the PS4?

This node is generated by the package [controller_manager](http://wiki.ros.org/controller_manager) and creates a ROS layer that receives topics to move your custom hardware. I found that [this line](https://github.com/eborghi10/my_ROS_mobile_robot/blob/master/my_robot_base/include/my_robot_hw_interface.h#L175) sets the maximum output velocity. You should change it. 

**Suggestion:** This code could contain bugs because I didn't have time to debug it a lot. 
If you see [below on the code](https://github.com/eborghi10/my_ROS_mobile_robot/blob/master/my_robot_base/include/my_robot_hw_interface.h#L199), you will find that I'm using a double to receive the velocity commands on the Arduino. But on another repository I have a [better implementation of the Arduino node](https://github.com/eborghi10/ROS-UTN/tree/master/MyRobotRos) (sorry for the mess, I think I didn't update this repo yet) where I used UINT16 as output format (0-255).  I recommend you to change the file `my_robot_hw_interface.h` file so both codes can interact with each other.

 Another thing that you can do is to leave the controller_manager code as it is now and modify the Arduino node in order to receive velocity commands in rad/s and you will need to create a function that satisfies a condition like `max_speed (in rad/s) == 255`.

**Comment by agrytnes** [comment]
Ok! The problem was a combination of the speed limit and me being confused with what values(range of values) to write and read on the cmd_vel and wheel_vel topics. I can now continue adapting your code to my own robot. Thank you very much!

**Comment by eborghi10** [comment]
Great, I hope you can get it work and if you think that any of your changes can help this repo, feel free to create a PR!
