### ISSUE TITLE
Robot not Loading the Caster Wheels

### ISSUE THREAD

**Issue by yuriloia** [eborghi10/my_ROS_mobile_robot#6]
Hi, I've recently try to use your packege in the Ros Melodic, I don't know what is the problem, but when I launch the gazebo package it does not load the caster wheel image. 

Also, on the Rviz there are error messages on the camera link, on the caster_wheel, on the hokuyo link, on the left and right wheel, they all say that "there is no transform from the base link to them".

Could you please help me solve it

**Comment by eborghi10** [comment]
Hi @yuriloia , I didn't try the simulation with Melodic recently.

In order to make it work, you should install from source two packages: `turtlebot_teleop` and `turtlebot_gazebo`, because they're not available as Debian packages.

In my case, I commented them out and replaced [this](https://github.com/eborghi10/my_ROS_mobile_robot/blob/master/my_robot_gazebo/launch/my_robot_world.launch#L23) with `default=" "`. Then, I ran the following commands:

```sh
rosdep install --from-path src -yi

catkin_make

source devel/setup.bash

roslaunch my_robot_gazebo my_robot_world.launch
```
----

I could replicate your issue with the caster wheel. The interesting thing is that I can see the collision model. And this is why the robot is not falling down:

![image](https://user-images.githubusercontent.com/3400230/67162236-777e6100-f338-11e9-90b9-fcd1bb151d71.png)

I could make it work opening the file caster_wheel.dae and converting it to STL using FreeCAD and changing [this line](https://github.com/eborghi10/my_ROS_mobile_robot/blob/master/my_robot_description/urdf/my_robot.xacro#L89) by:

```xml
<mesh filename="package://my_robot_description/meshes/caster_wheel.stl" scale="0.001 0.001 0.001"/>
```

![image](https://user-images.githubusercontent.com/3400230/67162374-ba8d0400-f339-11e9-8621-bc6a28025efb.png)

If you want to add a texture/color, check how it's being done for the wheels.

----

Regarding Tf, I'm seeing it correctly:

![image](https://user-images.githubusercontent.com/3400230/67162393-0049cc80-f33a-11e9-90dc-ff4b7b968176.png)

You can see this open `rqt` and then: `Plugins -> Visualization -> TF Tree`.
