### ISSUE TITLE
Dependency on JointStateController and JointEffortController

### ISSUE THREAD

**Issue by fjp** [eborghi10/my_ROS_mobile_robot#7]
Hi, thank you for this great repository implementing the `diff_drive_controller`. 

I have two questions regarding the controllers you use. In [my_robot_control.yaml](https://github.com/eborghi10/my_ROS_mobile_robot/blob/master/my_robot_control/config/my_robot_control.yaml) you specify `joint_state_controller/JointStateController` and two `effort_controllers/JointEffortController` controllers. 

1. Is `joint_state_controller/JointStateController` required when working with real robot hardware to publish the `jointState` messages?
2. Why do you need the `effort_controllers/JointEffortController`s? I thought that `diff_drive_controller` (configured in [my_robot_common.yaml](https://github.com/eborghi10/my_ROS_mobile_robot/blob/master/my_robot_control/config/my_robot_common.yaml)) is controlling the two wheels (reading encoder vaules and writing (velocity?) commands) and shouldn't require the two `effort_controllers/JointEffortController`s. 

Please let me know why these controllers are needed.

**Comment by eborghi10** [comment]
Hi @fjp, I didn't work on this repo for a long time. I'll try to remember but thanks for raising your concerns.

1. Yes, because that's the way we tell the whole system the current status of your joints. If another code wants to do something with the velocity of the joints, for example, here is where it should look for.

2. I was discussing this the other day with a work teammate. I don't remember why I used `effort_controllers/JointEffortController`s instead of `diff_drive_controller`. You should use the last one because you will have the diff-drive logic already implemented.

**Comment by fjp** [comment]
@eborghi10 thank you for your answer and the helpful advice. I'll try to go without the `effort_controllers` and just use `joint_state_controller` and `diff_drive_controller`.
